using System.Text;
using FluentAssertions;
using System.Linq;
using Cache = System.Collections.Concurrent.ConcurrentDictionary<(string, int), long>;

namespace AdventOfCode.Tests.Y2024.D11;

[ChallengeName("Plutonian Pebbles")]
public class Y2024D11
{
    private readonly string _input = File.ReadAllText(@"Y2024\D11\Y2024D11-input.txt", Encoding.UTF8);

    [Fact]
    public void PartOne()
    {
        var output = StoneCount(_input, 25);

        output.Should().Be(218079);
    }

    [Fact]
    public void PartTwo()
    {
        var output = StoneCount(_input, 75);

        output.Should().Be(259755538429618);
    }


    long StoneCount(string input, int blinks)
    {
        var cache = new Cache();
        return input.Split(" ").Sum(n => Eval(long.Parse(n), blinks, cache));
    }

    // Recursively calculates the total number of stones generated by a single engravement (n)
    // after a specified number of blinks. Uses caching to optimize and prevent exponential
    // computation by storing intermediate results.
    long Eval(long n, int blinks, Cache cache) =>
        cache.GetOrAdd((n.ToString(), blinks), key =>
            key switch
            {
                (_, 0) => 1,

                ("0", _) =>
                    Eval(1, blinks - 1, cache),

                (var st, _) when st.Length % 2 == 0 =>
                    Eval(long.Parse(st[0..(st.Length / 2)]), blinks - 1, cache) +
                    Eval(long.Parse(st[(st.Length / 2)..]), blinks - 1, cache),

                _ =>
                    Eval(2024 * n, blinks - 1, cache)
            }
        );
}